### ISSUE TITLE
Apple sign in - hide e-mail - crashes My Profile screen

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#149]
Apple sign in - hide e-mail - crashes My Profile screen

If user chooses to "hide my e-mail".

**Comment by dzinzyura** [comment]
Done. The bug is fixed by adding [the Requesting modal for First&Last names](https://github.com/dappros/ethora/issues/147)

Thank you, @transkarpation @dendidibe @bikash-code!

[Video of testing](https://dappros.slack.com/archives/C025G04FQV6/p1662111733568839?thread_ts=1662103156.211559&cid=C025G04FQV6)
