### ISSUE TITLE
NFT provenance (history) screen update

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#274]
Please update captions here to make it more clear what's happening:

first entry like this:
collection deployed 🔗📜 by [**User Name**]

second entry like this:
[X]🖼️ (of [X] total) NFTs minted 🔗 by  [**User Name**]

<img width="586" alt="Screenshot 2022-12-20 at 16 40 08" src="https://user-images.githubusercontent.com/328787/208719243-8023a213-4cfd-4e4c-ac23-b34d03b22660.png">

**Comment by phwizard** [comment]
Can we also fix here:

I have 'purchased' a free token here.
Instead of showing a transfer from me to me, let's show:

Purchased by User Name for 🪙X

In my case:
Purchased by Taras Filatov for 🪙0

Also please display the trait / type tag ("paper" in this case) in the item description section under item name

![Screenshot_2022-12-20-23-17-00-939_com.ethora.jpg](https://user-images.githubusercontent.com/328787/208784508-6c98378a-1205-4972-9613-8239a0d47611.jpg)

**Comment by dendidibe** [comment]
@phwizard for this NFTs minted 🔗 by , it will cover also second case i think, because if there is sender and receiver is the same man, then it is mint
<img width="327" alt="Снимок экрана 2022-12-21 в 12 06 26" src="https://user-images.githubusercontent.com/54039544/208878803-460a01d1-4602-4cff-a00b-1ab2341fc7d9.png">

**Comment by dzinzyura** [comment]
Thanks, Misha!

[Build for review](https://dappros.slack.com/archives/C025G04FQV6/p1671618382276689)
