### ISSUE TITLE
Web - bug: 'read only' when joining a new chat room by link

### ISSUE THREAD

**Issue by phwizard** [dappros/ethora#494]
**Describe the bug**
Other users can't write into a room they joined via a short link.

**To Reproduce**
1. Create a new chat room
2. Share link with another user
3. Another user joins the room
4. Another user sees the room but cannot write messages

**Expected behavior**
Another user can write messages.

**Screenshots**
<img width="719" alt="Screenshot 2023-08-10 at 11 21 37" src="https://github.com/dappros/ethora/assets/328787/d95aba23-ed44-4eaa-a670-9fb2bd927bc5">

**Additional context**
We had this in the past. Probably XMPP related.

**Comment by dzinzyura** [comment]
@Akick could you please check if this issue's XMPP related once you have a chance.

thank you

**Comment by dzinzyura** [comment]
as discussed with Oleksii - it's not related not XMPP

**Comment by phwizard** [comment]
when pressing on the link we need to first wait for XMPP / verify which rooms user is subscribed to or now

unlike standard scenario when we know which rooms users is subscribed to already

**Comment by dzinzyura** [comment]
**Goal:**
Fix the read-only bug with the subscription for the room, when joining via the link

**Affected metric:**
- UI / UX enhancements
- Ease of data handling
- Ease of messaging operations

**Story:**
As a user, when I receive a link for the chat room, I open it and join (subscribing) the room. I can read message as well as send own ones.

**Description:**
Implement the possibility for the users to subscribe the room when joining via the link, so that messages can not only be read, but also users will be able to send their own messages - to fully use the chat features.

@dendidibe

**Comment by phwizard** [comment]
Now we have added a button "Join room" to handle this
