### ISSUE TITLE
Latest version of react-native-reanimated "^3.2.0", not working for Android

### ISSUE THREAD

**Issue by quavo19** [dappros/ethora#508]
hello @phwizard, [this](https://github.com/dappros/ethora/issues/504) issue was not resolved after i installed NDK version 21.4.7.  The build command for Android still didn't progress after building 72% and it didn't show any error logs as I said earlier. what else can I do now?

**Comment by dzinzyura** [comment]
Hi, @quavo19 !

We just had a team discussion to do our best to help you. 

We suppose that it can be a local problem on your side, because we've tried to install and there weren't any issues. 

Maybe you could provide us more details, so that we can dive deeper into the problem you faced. 

Best regards, 
Vladyslav
Ethora team

**Comment by quavo19** [comment]
@dzinzyura thanks for the quick response, I will try other ways to resolve this. if anything comes up I'll inform you

**Comment by dzinzyura** [comment]
sure. we're always happy to help! feel free to ping us if you need any help
