### ISSUE TITLE
Design - Profile screen - Transactions

### ISSUE THREAD

**Issue by dzinzyura** [dappros/ethora#537]
**Goal:**
Introduce an updated vision for Transactions menu and its details. 

**Affected metric:**
- UI/UX enhancement
- Ease of data handling

**Description:**
Create designs for Transactions screens. Please, use these details and descriptions for future works:

**Transactions screen (old):**

![image](https://github.com/dappros/ethora/assets/99117374/33844a21-eb86-4a38-a04e-b0bd4f52e916)

**Transaction details:**

![image](https://github.com/dappros/ethora/assets/99117374/35a7229a-d45f-4ef7-9a4a-df5a1c0bffdf)

![image](https://github.com/dappros/ethora/assets/99117374/a668ea9c-c33a-4821-b600-3fdbc87ac743)

**[PROFILE SCREEN EPIC](https://github.com/dappros/ethora/issues/535)**

**Comment by phwizard** [comment]
Regarding Transactions UI, this looks good preliminary

<img width="682" alt="Screenshot 2023-12-11 at 11 33 07" src="https://github.com/dappros/ethora/assets/328787/3256482a-42f9-4c3a-89cf-6808404022f1">

Please add the amount of the asset sent or received as well (see details below) plus asset icon (coin icon).

Also - see if a variation with green down (received) and red up (sent) arrow works instead of Received / Sent? Like in one of our existing screens below.


---

Let me add something I forgot to emphasise before.

See 2 screenshots below, as I believe I only showed this UI

<img width="187" alt="Screenshot 2023-12-11 at 11 35 50" src="https://github.com/dappros/ethora/assets/328787/e60d72f0-1f33-4b30-8875-b5d491ec2c01">

which is older design and doesn't do justice to what's possible in Transactions UI and what was implemented later.

What you did by showing just the counterparty name is  a good approach, however what I missed adding is that we should also show how much is transferred like here: 

<img width="276" alt="Screenshot 2023-12-11 at 11 40 03" src="https://github.com/dappros/ethora/assets/328787/4f52ef60-440e-44b6-a6f5-4ca2699019e7">

(BTW When you unroll the transaction, the amount of coins or assets transferred is shown in "Value" field which can be anything starting from 1.)

above shows that I have transferred 100 Coins to Merchant Bot, then the NFT Collection Contract called "UAXmasByTitov" has transferred 100 items to me and then same contract transferred 1000 items for me. 
(I'm saying 'items' because I'm not sure if it was coins, it could be 100 items of the NFT collection but the app used the coin icon because it didn't have a separate icon for other types of assets). 

Note that often transactions will be of Coin asset type - just use our standard Coin icon for those.

You don't have to design other icons for other asset types (documents, NFT collections) at this point. We will use (1) emojis or (2) small asset image thumbnails, or (3) design special icon / icons for them at a later point.


<img width="268" alt="Screenshot 2023-12-11 at 11 31 31" src="https://github.com/dappros/ethora/assets/328787/67336eee-372a-4fd7-969f-9b8cbea7c55d">

<img width="268" alt="Screenshot 2023-12-11 at 11 32 06" src="https://github.com/dappros/ethora/assets/328787/d4c16d27-6ff7-4a5a-ab7a-fcc3477a3f9d">

fyi @polipivnenko

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/4d627107-2c43-42ec-b97b-38558f4b5461)

Updated detailed transaction wireframes.
I changed the caption below the main text, added a caption indicating who the transaction is from or to. I believe this information will be more useful to the user than the current coin balance at the time of receiving transactions.

@phwizard @dzinzyura

**Comment by phwizard** [comment]
Looks great, thank you!

**Comment by phwizard** [comment]
as discussed in the other issue, maybe we should get rid of this button and keep the transactions count in there, otherwise this one is also good to implement

<img width="137" alt="Screenshot 2023-12-13 at 10 39 42" src="https://github.com/dappros/ethora/assets/328787/f3731047-f515-4996-a658-353b330e5270">

**Comment by polipivnenko** [comment]
![image](https://github.com/dappros/ethora/assets/149969403/da00f224-ea64-4db2-9556-c700ce17043c)
@dzinzyura @phwizard
